DVCP/Controllers/AdminController.cs
using DVCP.CommonData;
using DVCP.Models;
using DVCP.ViewModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
namespace DVCP.Controllers
{
    [Authorize(Roles = "admin,editor")]
    public class AdminController : Controller
    {
        UnitOfWork db = new UnitOfWork(new DVCPContext());
        //[Authorize(Roles ="admin,editor")]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult newPost()
        {
            newPostViewModel model = new newPostViewModel
            {
                post_type = PostType.Normal,
                post_tag = PostData.getTagList(), //PostData.getTagList(),
                Status = true,
                changeAvatar = true,
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult newPost(newPostViewModel model)
        {
            List<Tag> taglist = new List<Tag>();
            taglist.AddRange(model.post_tag.Where(m => m.Selected)
                .Select(m => new Tag { TagID = int.Parse(m.Value), TagName = m.Text })
                );
           
            if (ModelState.IsValid && taglist.Count > 0)
            {
               
                if (model.post_teaser == null || model.post_teaser.Length <= 20)
                {
                    model.post_teaser = CommonFunction.GetTeaserFromContent(model.post_content, 200);
                }
               
                bool isSavedSuccessfully = true;
                try
                {
                    if (model.avatarFile != null && model.avatarFile.ContentLength > 0)
                    {
                        string subPath = Server.MapPath("~/Upload/images/");
                        bool exists = System.IO.Directory.Exists(subPath);
                        if (!exists)
                        {
                            System.IO.Directory.CreateDirectory(subPath);
                        }
                        string extension = Path.GetExtension(model.avatarFile.FileName);
                        model.AvatarImage = SlugGenerator.SlugGenerator.GenerateSlug(model.post_title) +"-"+ new Random().Next(1,100) + extension;
                        model.avatarFile.SaveAs(Server.MapPath("~/Upload/images/") + model.AvatarImage);
                    }
                }
                catch (Exception ex)
                {
                    isSavedSuccessfully = false;
                }
                if (isSavedSuccessfully == true)
                {
                    User user = db.userRepository.FindByUsername(User.Identity.Name);
                    Post pOST = new Post
                    {
                        userid = user.userid,
                        dynasty = model.dynasty.ToString(),
                        create_date = DateTime.Now,
                        AvatarImage = model.AvatarImage,
                        post_content = model.post_content,
                        post_review = model.post_review,
                        post_title = model.post_title,
                        post_type = (int)model.post_type,
                        ViewCount = 0,
                        Rated = (int)model.Rated,
                        post_teaser = model.post_teaser,
                        status = model.Status,
                        post_tag = model.meta_tag,
                    };
                    foreach(var i in taglist)
                    {
                        Tag tags = db.tagRepository.FindByID(i.TagID);
                        pOST.Tbl_Tags.Add(tags);
                        tags.Tbl_POST.Add(pOST);
                    }
                    string slug = SlugGenerator.SlugGenerator.GenerateSlug(pOST.post_title.ToLower());
                    pOST.post_slug = slug;
                    if(db.postRepository.AllPosts().Any(m=>m.post_slug == slug))
                    {
                        pOST.post_slug = slug + "-" + 1;
                    }
                    db.postRepository.AddPost(pOST);
                    db.Commit();
                    if (model.post_type.Equals(PostType.Slide))
                    {
                        return View("UploadImage", new uploadViewModel { id = pOST.post_id, title = pOST.post_title });
                    }
                    return RedirectToAction("ListPost");
                }
            }
            // nếu lỗi thì đẩy về tiếp
            //newPostViewModel nmodel = new newPostViewModel
            //{
            //    post_type = PostType.Normal,
            //    post_tag = PostData.getTagList(),
            //};

            return View(model);
        }
        [Authorize(Roles = "admin")]
        public ActionResult ListPost(string sortOrder, string CurrentSort, int? page, string titleStr)
        {
            //DVCPContext db = new DVCPContext();
            int pageSize = 100;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            ViewBag.CurrentSort = sortOrder;
            sortOrder = String.IsNullOrEmpty(sortOrder) ? "Title" : sortOrder;
            IPagedList<Post> post = null;
            ViewBag.Sort = "tăng dần";
            if (String.IsNullOrWhiteSpace(titleStr))
            {
                switch (sortOrder)
                {
                    case "Title":
                        ViewBag.sortname = "tiêu đề";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            ViewBag.Sort = "giảm dần";
                            post = db.postRepository.AllPosts().OrderByDescending
                                    (m => m.post_title).ToPagedList(pageIndex, pageSize);
                        }

                        else
                        {
                            post = db.postRepository.AllPosts().OrderBy
                                    (m => m.post_title).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    case "CreateDate":
                        ViewBag.sortname = "ngày tạo";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            ViewBag.Sort = "giảm dần";
                            post = db.postRepository.AllPosts().OrderByDescending
                                    (m => m.create_date).ToPagedList(pageIndex, pageSize);
                        }

                        else
                        {
                            post = db.postRepository.AllPosts().OrderBy
                                    (m => m.create_date).ToPagedList(pageIndex, pageSize);
                        }

                        break;
                    case "ViewCount":
                        ViewBag.sortname = "lượt xem";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            ViewBag.Sort = "giảm dần";
                            post = db.postRepository.AllPosts().OrderByDescending
                                    (m => m.ViewCount).ToPagedList(pageIndex, pageSize);
                        }

                        else
                        {
                            post = db.postRepository.AllPosts().OrderBy
                                    (m => m.ViewCount).ToPagedList(pageIndex, pageSize);
                        }

                        break;
                        //default:
                        //    post = UnitOfWork.postRepository.AllPosts().ToPagedList(pageIndex, pageSize);
                        //    break;
                }
            }
            else
            {
                ViewBag.titleStr = titleStr;
                switch (sortOrder)
                {
                    case "Title":
                        ViewBag.sortname = "tiêu đề";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            ViewBag.Sort = "giảm dần";
                            post = db.postRepository.AllPosts().Where(m => m.post_title.ToLower().Contains(titleStr.ToLower())).OrderByDescending
                                    (m => m.post_title).ToPagedList(pageIndex, pageSize);
                        }
                        else
                        {
                            post = db.postRepository.AllPosts().Where(m => m.post_title.ToLower().Contains(titleStr.ToLower())).OrderBy
                                      (m => m.post_title).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    case "CreateDate":
                        ViewBag.sortname = "ngày tạo";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            ViewBag.Sort = "giảm dần";
                            post = db.postRepository.AllPosts().Where(m => m.post_title.ToLower().Contains(titleStr.ToLower())).OrderByDescending
                                    (m => m.create_date).ToPagedList(pageIndex, pageSize);
                        }

                        else
                        {
                            post = db.postRepository.AllPosts().Where(m => m.post_title.ToLower().Contains(titleStr.ToLower())).OrderBy
                                   (m => m.create_date).ToPagedList(pageIndex, pageSize);
                        }
                        break;
                    case "ViewCount":
                        ViewBag.sortname = "lượt xem";
                        if (sortOrder.Equals(CurrentSort))
                        {
                            ViewBag.Sort = "giảm dần";
                            post = db.postRepository.AllPosts().Where(m => m.post_title.ToLower().Contains(titleStr.ToLower())).OrderByDescending
                                    (m => m.ViewCount).ToPagedList(pageIndex, pageSize);

DVCP/Controllers/FileController.cs
using ElFinder;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DVCP.Controllers
{
    public class FileController : Controller
    {
        public virtual ActionResult Index(string folder, string subFolder)
        {
            var driver = new FileSystemDriver();

            var root = new Root(new DirectoryInfo(Server.MapPath("~/Upload/" + folder)),
                "http://" + Request.Url.Authority + "/Upload/" + folder + "/")
            {
                IsReadOnly = false,
                Alias = "Root",
                MaxUploadSizeInMb = 100
            };

            if (!string.IsNullOrEmpty(subFolder))
            {
                root.StartPath = new DirectoryInfo(Server.MapPath("~/Upload/" + folder + "/" + subFolder));
            }

            driver.AddRoot(root);
            var connector = new Connector(driver);
            return connector.Process(HttpContext.Request);
        }

        public virtual ActionResult SelectFile(string target)
        {
            var driver = new FileSystemDriver();

            driver.AddRoot(
                new Root(
                    new DirectoryInfo(Server.MapPath("~/Upload")),
                    "http://" + Request.Url.Authority + "/Upload")
                { IsReadOnly = false });

            var connector = new Connector(driver);

            return Json(connector.GetFileByHash(target).FullName);
        }
    }

}

DVCP/Controllers/UserController.cs
using DVCP.Models;
using DVCP.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DVCP.Controllers
{
    public class UserController : Controller
    {
        UnitOfWork UnitOfWork = new UnitOfWork(new DVCPContext());
        // GET: User
        public ActionResult Login()
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        [Authorize(Roles = "admin")]
        public ActionResult UserManager()
        {
           List<User> lstUser = UnitOfWork.userRepository.AllUsers().ToList();
           return View(lstUser);
        }
        public void setCookie(string username, bool rememberme = false, string role = "normal")
        {
            var authTicket = new FormsAuthenticationTicket(
                               1,
                               username,
                               DateTime.Now,
                               DateTime.Now.AddMinutes(120),
                               rememberme,
                               role
                               );

            string encryptedTicket = FormsAuthentication.Encrypt(authTicket);

            var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
            Response.Cookies.Add(authCookie);
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string ReturnUrl)
        {

            if (ModelState.IsValid)
            {
                User user = UnitOfWork.userRepository.FindByUsername(model.Username);
                if (user != null)
                {
                    if (user.password == CommonData.CommonFunction.CalculateMD5Hash(model.Password) && user.status == true)
                    {
                        setCookie(user.username, model.RememberMe, user.userrole);
                        if (ReturnUrl != null)
                            return Redirect(ReturnUrl);
                        return RedirectToAction("Index", "Home");
                    }
                    ViewBag.Error = "Sai tài khoản hoặc mật khẩu!";
                    return View();

                }
            }
            
            ViewBag.Error = "Wrong username or password!";
            return View();
        }
        [Authorize(Roles="admin")]
        public ActionResult createUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult createUser(userListViewModel model)
        {
            if(ModelState.IsValid)
            {
                User user = UnitOfWork.userRepository.FindByUsername(model.username);
                if(user == null)
                {
                    User nuser = new User
                    {
                        username = model.username,
                        fullname = model.fullname,
                        status = true,
                        userrole = "editor",
                        password = CommonData.CommonFunction.CalculateMD5Hash(model.password)
                    };
                    UnitOfWork.userRepository.Add(nuser);
                    UnitOfWork.Commit();
                    return RedirectToAction("UserManager");
                }
                else
                {
                    ViewBag.anno = "Tên người dùng này đã tồn tại";
                    return View();
                }
            }
            return View();
        }
        [Authorize]
        public ActionResult ChangePass()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePass(changepassViewModel model)
        {
            if(ModelState.IsValid)
            {
                if(model.oldpassword == model.password)
                {
                    ViewBag.anno = "Mật khẩu mới không được trùng mật khẩu cũ !";
                    return View();
                }
                else
                {
                    User user = UnitOfWork.userRepository.FindByUsername(User.Identity.Name);
                    if(user != null)
                    {
                        user.password = CommonData.CommonFunction.CalculateMD5Hash(model.password);
                        UnitOfWork.Commit();
                        return RedirectToAction("Logout");
                    }
                }
            }
            return View();
        }
        [Authorize(Roles="admin")]
        public JsonResult changeStatus(int userid,bool state = true)
        {
            string prefix = state ? "Đã bỏ cấm" : "Đã cấm";
            User u = UnitOfWork.userRepository.FindByID(userid);
            if(u.username != "admin")
            {
                u.status = state;
                UnitOfWork.Commit();
                return Json(new { Message = prefix + " \"" + u.username + "\"" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Message = "Không được cấm admin" }, JsonRequestBehavior.AllowGet);
        }
    }
}

DVCP/Views/Shared/FilesForm.cshtml
@{
    ViewBag.Title = "Files";
}
<link href="~/Content/elfinder/css/elfinder.full.css" rel="stylesheet" />
<script src="~/Content/elfinder/js/elfinder.min.js"></script>

<script type="text/javascript">
    $(function ()
    {
        var myCommands = elFinder.prototype._options.commands;
        var disabled = ['extract', 'archive', 'resize', 'help', 'select']; // Not yet implemented commands in ElFinder.Net
        $.each(disabled, function (i, cmd)
        {
            (idx = $.inArray(cmd, myCommands)) !== -1 && myCommands.splice(idx, 1);
        });
        var selectedFile = null;
        var options = {
            url: '/connector', // connector route defined in \App_Start\RouteConfig.cs
            customData: { folder: '@Model.Folder', subFolder: '@Model.SubFolder' }, // customData passed in every request to the connector as query strings. These values are used in FileController's Index method.
            rememberLastDir: false, // Prevent elFinder saving in the Browser LocalStorage the last visited directory
            commands: myCommands,
            //lang: 'pt_BR', // elFinder supports UI and messages localization. Check the folder Content\elfinder\js\i18n for all available languages. Be sure to include the corresponding .js file(s) in the JavaScript bundle.
            uiOptions: { // UI buttons available to the user
                toolbar: [
                    ['back', 'forward'],
                    ['reload'],
                    ['home', 'up'],
                    ['mkdir', 'mkfile', 'upload'],
                    ['open', 'download'],
                    ['info'],
                    ['quicklook'],
                    ['copy', 'cut', 'paste'],
                    ['rm'],
                    ['duplicate', 'rename', 'edit'],
                    ['view', 'sort']
                ],
                navbar: {
                    minWidth: 150,
                    maxWidth: 500
                }
            },
            handlers: {
                select: function (event, elfinderInstance)
                {
                    if (event.data.selected.length == 1)
                    {
                        var item = $('#' + event.data.selected[0]);
                        if (!item.hasClass('directory'))
                        {
                            selectedFile = event.data.selected[0];
                            $('#elfinder-selectFile').show();
                            return;
                        }
                    }
                    $('#elfinder-selectFile').hide();
                    selectedFile = null;
                }
            }
        };
        $('#elfinder').elfinder(options).elfinder('instance');
        $('.elfinder-toolbar:first').append('<div class="ui-widget-content ui-corner-all elfinder-buttonset" id="elfinder-selectFile" style="display:none; float:right;">' +
        '<div class="ui-state-default elfinder-button" title="Select" style="width: 100px;"></div>');
        $('#elfinder-selectFile').click(function ()
        {
            if (selectedFile != null)
                $.post('file/selectFile', { target: selectedFile }, function (response)
                {
                    alert(response);
                });
        });
    });
</script>
<div id="elfinder"></div>

DVCP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HutechNews</title>
    <link rel="icon" href="~/Content/web/images/logoht.png" type="image/x-icon" />
    <link href="~/Content/web/styles.css" rel="stylesheet" />
    <link href="~/Content/web/web.css" rel="stylesheet" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:description" content="@ViewBag.Description" />
    <meta property="og:image" content="@ViewBag.Image" />
    <meta name="Description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Tag">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Expanded:400,600,700" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/AdminLTE/plugins/font-awesome/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="//fonts.googleapis.com/css?family=Merriweather:400,700%7CDroid+Serif:400,700" rel="stylesheet" type="text/css">
    @* @Scripts.Render("~/bundles/modernizr")*@
    @{
        GetData data = new GetData();
    }


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <header>
        <div class="bg-191">
            <div class="container">
                <div class="oflow-hidden color-ash font-9 text-sm-center ptb-sm-5">

                    <ul class="float-left list-a-plr-10 list-a-plr-sm-5 list-a-ptb-15 list-a-ptb-sm-10 toplink">
                        <li><a class="pl-0 pl-sm-10" href="">@DateTime.Now</a></li>
                        <li><a href="https://www.facebook.com/profile.php?id=100069792041010">Liên hệ</a></li>
                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Admin Panel", "Index", "Admin", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Logout", "Logout", "User", null, new { @class = "nav-link" })</li>
                        }
                    </ul>
                    <div class="d-inline-block float-right mt-2 mr-4">
                        <form action="/tim-kiem" method="get">
                            <input type="text" name="title" placeholder="Tìm kiếm" class="mr-2 txtSearch" /><button class="text-white" type="submit"><i class="fa fa-search"></i></button>
                            <a href="User/Login" id="userLink">
                                <i class="material-icons" href="User\Login">person</i>
                            </a>                           
                        </form>
                    </div>
                    @*<ul class="float-right float-sm-none list-a-plr-10 list-a-plr-sm-5 list-a-ptb-15 list-a-ptb-sm-5">
                            <li><a class="pl-0 pl-sm-10" href="#"><i class="fa fa-facebook-official"></i></a></li>

                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>*@
                </div>
            </div>
            <!-- container -->
        </div>

        <div class="container back-white">
            <a class="logo" href="/"><img src="~/Content/web/images/logoht.png" alt="Logo"></a>


            <a class="menu-nav-icon" data-menu="#main-menu" href="#"><i class="ion-navicon"></i></a>

            <ul class="main-menu2 link" id="main-menu">
                <li><a href="/">HOME</a></li>
                <li class="drop-down">
                    <a href="/danh-muc/">Kinh Doanh<i class="fa fa-caret-down"></i></a>
                    <ul class="drop-down-menu drop-down-inner">
                        <li><a href="/Category/Quocte">Quốc tế</a></li>
                        <li><a href="/Category/Doanhnghiep">Doanh Nghiệp</a></li>
                        <li><a href="/Category/Tenis">Chứng khoán</a></li>

                    </ul>
                </li>
                <li class="drop-down">
                    <a href="/danh-muc/">Thời sự<i class="fa fa-caret-down"></i></a>
                    <ul class="drop-down-menu drop-down-inner">
                        <li><a href="/Category/Dansinh">Dân sinh</a></li>
                        <li><a href="/Category/Giaothong">Giao thông</a></li>
                        <li><a href="/Category/LDVL">Lao động - việc làm</a></li>
                     
                    </ul>
                </li>
                <li class="drop-down">
                    <a href="/danh-muc/">Thể thao<i class="fa fa-caret-down"></i></a>
                    <ul class="drop-down-menu drop-down-inner">
                        <li><a href="/Home/Bongda">Bóng đá</a></li>
                        <li><a href="/Home/Tracnghiem">Trắc nghiệm</a></li>
                        <li><a href="/Home/Tenis">Tenis</a></li>
                        <li><a href="/Home/Bunesliga">Bunesliga</a></li>
                        <li><a href="/Home/Cacmonkhac">Các môn khác</a></li>
                    </ul>
                </li>
                <li><a href="/tim-kiem">Tìm theo thể loại</a></li>

            </ul>

            <div class="clearfix"></div>
        </div><!-- container -->
    </header>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="bg-191 color-ccc">

        <div class="container">
            <div class="pt-50 pb-20 pos-relative">
                <div class="abs-tblr pt-50 z--1 text-center">
                    @*<div class="h-80 pos-relative"><img class="opacty-1 h-100 w-auto" src="~/Content/web/images/map.png" alt=""></div>*@
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="mb-30">
                            <h5 class="color-primary mb-20"><b>FACEBOOK</b></h5>
                            <div class="fb-page" data-href="https://www.facebook.com/hutechuniversity/" data-tabs="timeline" data-width="" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/daivietcophong/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/daivietcophong/">Đại Việt Cổ Phong - 大越古風 - VietnamAncient</a></blockquote></div>
                        </div><!-- mb-30 -->
                    </div><!-- col-md-4 -->


                    <div class="col-sm-4">
                        <div class="mb-30">
                            <h5 class="color-primary mb-20"><b>ĐỀ XUẤT CAO</b></h5>
                            



                        </div><!-- mb-30 -->
                    </div><!-- col-md-4 -->
                    <div class="col-sm-4">
                        <div class="mb-30">
                            <a href="#"><img src="~/Content/web/images/logoht.png"></a>
                            <p class="mtb-20 color-ccc">
                                Trang tin tức của Hutech.
                            </p>
                            <p class="color-ash">
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> 

                            </p>
                        </div><!-- mb-30 -->
                    </div><!-- col-md-4 -->


                </div><!-- row -->
            </div><!-- ptb-50 -->

            <div class="brdr-ash-1 opacty-2"></div>

            <div class="oflow-hidden color-ash font-9 text-sm-center ptb-sm-5">

               

            </div>
        </div>
    </footer>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.3"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/web/tether.min.js"></script>
    <script src="~/Content/web/scripts.js"></script>
    <script src="~/Content/photoswipe/init.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>